// Builds the self-contained entry.js for a "js-algo" chsengine package.
// The generated file is a classic (non-module) Worker script: it uses
// importScripts, so it never touches ESM syntax, and it bundles the user's
// evaluate(chess) function verbatim.

export const DEFAULT_EVALUATE_SOURCE = `function evaluate(chess) {
  // Return a score in centipawns FROM THE PERSPECTIVE OF THE SIDE TO MOVE.
  // Positive = good for the side to move, negative = bad. The search shell
  // takes care of negamax sign flipping, so you never need to think about
  // "white vs black" in here, only "me vs opponent".
  var values = { p: 100, n: 320, b: 330, r: 500, q: 900, k: 0 };
  var board = chess.board();
  var score = 0;
  for (var r = 0; r < 8; r++) {
    for (var f = 0; f < 8; f++) {
      var piece = board[r][f];
      if (!piece) continue;
      var value = values[piece.type];
      score += piece.color === chess.turn() ? value : -value;
    }
  }
  return score;
}`;

const TEMPLATE = `// AUTO-GENERATED by chsengine builder (kind: js-algo). Do not hand-edit the
// search shell below unless you know what you're doing -- your evaluate()
// function is the part meant to be edited, and it lives further down.
//
// Runtime contract: one postMessage line in, one postMessage line out, plain
// UCI text, no envelope. See the chsengine v1 format spec for details.

var ASSET_URLS = {};
try {
  ASSET_URLS = JSON.parse(decodeURIComponent(self.location.hash.slice(1)));
} catch (e) {
  ASSET_URLS = {};
}
importScripts(ASSET_URLS['chesslib.js']);
var Chess = self.ChessLib.Chess;

var ENGINE_NAME = /*__ENGINE_NAME__*/ "engine";
var ENGINE_AUTHOR = /*__ENGINE_AUTHOR__*/ "unknown";

var DEFAULT_MAX_DEPTH = /*__DEFAULT_DEPTH__*/ 4;
var DEFAULT_MOVETIME_MS = /*__DEFAULT_MOVETIME__*/ 4000;
var HARD_SAFETY_MS = 15000; // absolute cap even for "go infinite"
var MATE_SCORE = 100000;

// Cheap material table used ONLY by the search shell for quiescence move
// ordering (MVV-LVA-ish). This is intentionally separate from whatever
// material weights the user's evaluate() below uses.
var QSEARCH_PIECE_VALUES = { p: 100, n: 320, b: 330, r: 500, q: 900, k: 0 };
var QUIESCENCE_MAX_PLY = 6; // caps runaway capture chains (e.g. many pawns on one file)

// ---------------------------------------------------------------------
// Your evaluation function. Signature: evaluate(chess) -> number (centipawns,
// positive = good for the side to move). chess is a live chess.js instance.
// ---------------------------------------------------------------------
/*__USER_EVALUATE__*/

var chess = new Chess();
var searchState = { stop: false };

function send(line) {
  postMessage(line);
}

function toUciMove(move) {
  return move.from + move.to + (move.promotion || '');
}

function orderedMoves(c) {
  // Captures first. This is a cheap move-ordering heuristic that meaningfully
  // improves alpha-beta pruning without needing a real MVV-LVA table.
  var moves = c.moves({ verbose: true });
  moves.sort(function (a, b) {
    var av = a.flags.indexOf('c') !== -1 ? 1 : 0;
    var bv = b.flags.indexOf('c') !== -1 ? 1 : 0;
    return bv - av;
  });
  return moves;
}

function evaluateOrTerminal(c) {
  if (c.in_checkmate()) return -MATE_SCORE;
  if (c.in_draw() || c.in_stalemate() || c.in_threefold_repetition()) return 0;
  return evaluate(c);
}

// ---------------------------------------------------------------------
// Quiescence search. Fixed-depth negamax cuts off mid-capture-sequence and
// evaluates a position where material has just been won but not yet taken
// back -- the classic "horizon effect" that causes obvious blunders like
// grabbing a piece that's simply recaptured for a loss. Quiescence extends
// the search along CAPTURES ONLY until the position is quiet, so the eval
// at the true leaf reflects a stable material picture.
// ---------------------------------------------------------------------
function quiescence(c, alpha, beta, deadline, nodeCounter, qply) {
  nodeCounter.count++;

  if (c.in_checkmate()) return -MATE_SCORE;
  if (c.in_draw() || c.in_stalemate() || c.in_threefold_repetition()) return 0;

  if (nodeCounter.count % 4096 === 0 && Date.now() > deadline) {
    searchState.stop = true;
    return evaluate(c);
  }

  // Stand-pat: the side to move isn't forced to capture, so the "do
  // nothing" evaluation is itself a valid lower bound.
  var standPat = evaluate(c);
  if (standPat >= beta) return beta;
  if (standPat > alpha) alpha = standPat;
  if (qply <= 0) return alpha;

  var moves = c.moves({ verbose: true }).filter(function (m) {
    return m.flags.indexOf('c') !== -1 || m.flags.indexOf('e') !== -1;
  });
  moves.sort(function (a, b) {
    var av = QSEARCH_PIECE_VALUES[a.captured] || 0;
    var bv = QSEARCH_PIECE_VALUES[b.captured] || 0;
    return bv - av;
  });

  for (var i = 0; i < moves.length; i++) {
    c.move(moves[i]);
    var score = -quiescence(c, -beta, -alpha, deadline, nodeCounter, qply - 1);
    c.undo();
    if (searchState.stop) return alpha;
    if (score >= beta) return beta;
    if (score > alpha) alpha = score;
  }
  return alpha;
}

function negamax(c, depth, alpha, beta, deadline, nodeCounter) {
  nodeCounter.count++;
  if (depth === 0 || c.game_over()) {
    return quiescence(c, alpha, beta, deadline, nodeCounter, QUIESCENCE_MAX_PLY);
  }
  if (nodeCounter.count % 4096 === 0 && Date.now() > deadline) {
    searchState.stop = true;
    return evaluateOrTerminal(c);
  }
  var moves = orderedMoves(c);
  var best = -Infinity;
  for (var i = 0; i < moves.length; i++) {
    c.move(moves[i]);
    var score = -negamax(c, depth - 1, -beta, -alpha, deadline, nodeCounter);
    c.undo();
    if (score > best) best = score;
    if (best > alpha) alpha = best;
    if (alpha >= beta) break;
    if (searchState.stop) break;
  }
  return best;
}

function searchBestMove(maxDepth, deadline, startTime, nodeCounter) {
  var best = null;
  var bestScore = 0;
  var rootMoves = orderedMoves(chess);
  if (rootMoves.length === 0) return { move: null, score: 0 };

  for (var d = 1; d <= maxDepth; d++) {
    var iterBest = null;
    var iterBestScore = -Infinity;
    var alpha = -Infinity;
    var beta = Infinity;
    for (var i = 0; i < rootMoves.length; i++) {
      if (Date.now() > deadline || searchState.stop) break;
      chess.move(rootMoves[i]);
      var score = -negamax(chess, d - 1, -beta, -alpha, deadline, nodeCounter);
      chess.undo();
      if (score > iterBestScore) {
        iterBestScore = score;
        iterBest = rootMoves[i];
      }
      if (score > alpha) alpha = score;
    }
    if (iterBest) {
      best = iterBest;
      bestScore = iterBestScore;
      var elapsed = Math.max(1, Date.now() - startTime);
      send(
        'info depth ' + d +
        ' score cp ' + Math.round(bestScore) +
        ' nodes ' + nodeCounter.count +
        ' nps ' + Math.round(nodeCounter.count / (elapsed / 1000)) +
        ' time ' + elapsed +
        ' pv ' + toUciMove(best)
      );
    }
    if (Date.now() > deadline || searchState.stop) break;
  }
  return { move: best, score: bestScore };
}

function handlePosition(parts) {
  var idx = 1;
  if (parts[idx] === 'startpos') {
    chess = new Chess();
    idx++;
  } else if (parts[idx] === 'fen') {
    var fenParts = parts.slice(idx + 1, idx + 7);
    chess = new Chess(fenParts.join(' '));
    idx += 7;
  }
  if (parts[idx] === 'moves') {
    idx++;
    for (; idx < parts.length; idx++) {
      var m = parts[idx];
      chess.move({ from: m.slice(0, 2), to: m.slice(2, 4), promotion: m.slice(4, 5) || undefined });
    }
  }
}

function handleGo(parts) {
  searchState.stop = false;
  var depth = DEFAULT_MAX_DEPTH;
  var movetime = null;
  var infinite = false;
  for (var i = 1; i < parts.length; i++) {
    if (parts[i] === 'depth') depth = parseInt(parts[++i], 10);
    else if (parts[i] === 'movetime') movetime = parseInt(parts[++i], 10);
    else if (parts[i] === 'infinite') infinite = true;
  }
  var startTime = Date.now();
  var budget = movetime != null ? movetime : infinite ? HARD_SAFETY_MS : DEFAULT_MOVETIME_MS;
  var deadline = startTime + Math.min(budget, HARD_SAFETY_MS);
  var nodeCounter = { count: 0 };
  var result = searchBestMove(depth, deadline, startTime, nodeCounter);
  send('bestmove ' + (result.move ? toUciMove(result.move) : '(none)'));
}

self.onmessage = function (ev) {
  var line = String(ev.data);
  var parts = line.split(/\\s+/).filter(Boolean);
  var cmd = parts[0];

  if (cmd === 'uci') {
    send('id name ' + ENGINE_NAME);
    send('id author ' + ENGINE_AUTHOR);
    send('uciok');
  } else if (cmd === 'isready') {
    send('readyok');
  } else if (cmd === 'ucinewgame') {
    chess = new Chess();
  } else if (cmd === 'position') {
    handlePosition(parts);
  } else if (cmd === 'go') {
    handleGo(parts);
  } else if (cmd === 'stop') {
    searchState.stop = true;
  }
  // 'quit' and unrecognized 'setoption' lines are intentionally no-ops here.
};
`;

/**
 * @param {{ name: string, author: string, evaluateSource: string, defaultDepth?: number, defaultMovetime?: number }} opts
 * @returns {string} entry.js source text
 */
export function buildAlgoEntryJs({
  name,
  author,
  evaluateSource,
  defaultDepth = 4,
  defaultMovetime = 4000,
}) {
  return TEMPLATE.replace('/*__ENGINE_NAME__*/ "engine"', JSON.stringify(name || "engine"))
    .replace('/*__ENGINE_AUTHOR__*/ "unknown"', JSON.stringify(author || "unknown"))
    .replace('/*__DEFAULT_DEPTH__*/ 4', String(defaultDepth))
    .replace('/*__DEFAULT_MOVETIME__*/ 4000', String(defaultMovetime))
    .replace("/*__USER_EVALUATE__*/", evaluateSource);
}
