// Wrapper generator for converting an arbitrary Emscripten `-s MODULARIZE=1`
// UCI build into a chsengine package (wasmStrategy: "locateFile-module").
//
// Targets the addMessageListener/postMessage convention used by the
// mainstream Stockfish MODULARIZE/wasm builds (the same shape the official
// `stockfish` npm package exposes). If your build's factory function exposes
// a different bridge (raw stdout via Module.print, ccall-based hooks, etc.),
// edit the generated entry.js's bottom section -- everything above the
// "ENGINE BRIDGE" marker is boilerplate you shouldn't need to touch.

export function buildLocateFileModuleWrapper({ glueFilename, factoryName }) {
  return `// AUTO-GENERATED by chsengine builder (locateFile-module wrapper).
// Wraps an Emscripten "-s MODULARIZE=1 -s EXPORT_NAME=${factoryName}" build
// so it speaks the plain-postMessage UCI contract every chsengine package uses.

var ASSET_URLS = {};
try {
  ASSET_URLS = JSON.parse(decodeURIComponent(self.location.hash.slice(1)));
} catch (e) {
  ASSET_URLS = {};
}

importScripts(ASSET_URLS[${JSON.stringify(glueFilename)}]);

var pendingCommands = [];
var engineRef = null;

self.onmessage = function (ev) {
  if (engineRef) {
    engineRef.postMessage(ev.data);
  } else {
    pendingCommands.push(ev.data);
  }
};

// ---- ENGINE BRIDGE -------------------------------------------------------
// Adapt this block if your build's factory doesn't expose
// addMessageListener/postMessage. Everything above this line is boilerplate.
${factoryName}({
  locateFile: function (path) {
    return ASSET_URLS[path] || path;
  },
}).then(function (engine) {
  engineRef = engine;
  engine.addMessageListener(function (line) {
    postMessage(line);
  });
  while (pendingCommands.length > 0) {
    engine.postMessage(pendingCommands.shift());
  }
});
`;
}
