// Builds the self-contained entry.js for an "nn-onnx" chsengine package.
//
// Input/output contract your model must match (v1, documented for anyone
// training a model elsewhere and exporting to ONNX):
//   input  "input"  float32 [1, 768]  -- 12 planes (P N B R Q K p n b r q k)
//                                          x 64 squares, board() order
//                                          (rank 8 -> rank 1, file a -> h),
//                                          1.0 if that piece/color occupies
//                                          the square, else 0.0.
//   output "output" float32 [1, 1]    -- position value FROM THE PERSPECTIVE
//                                          OF THE SIDE TO MOVE, roughly in
//                                          pawn units (the driver multiplies
//                                          by 100 to report UCI centipawns).
//
// The ONNX runtime itself (onnxruntime-web) is loaded from a CDN at run
// time -- it is not bundled into the package -- so playing against an
// nn-onnx engine requires the browser to have internet access, even though
// the .chsengine.zip file itself is fully self-contained otherwise.

export const ONNX_RUNTIME_CDN_NOTE =
  "nn-onnx engines load onnxruntime-web from jsdelivr at run time. The .onnx model itself is bundled in the package, but running the engine needs internet access to fetch the runtime.";

const TEMPLATE = `// AUTO-GENERATED by chsengine builder (kind: nn-onnx).
//
// Runtime contract: one postMessage line in, one postMessage line out, plain
// UCI text, no envelope. See the chsengine v1 format spec for details.

var ASSET_URLS = {};
try {
  ASSET_URLS = JSON.parse(decodeURIComponent(self.location.hash.slice(1)));
} catch (e) {
  ASSET_URLS = {};
}
importScripts(ASSET_URLS['chesslib.js']);
var Chess = self.ChessLib.Chess;

importScripts('https://cdn.jsdelivr.net/npm/onnxruntime-web@1.19.2/dist/ort.min.js');
ort.env.wasm.wasmPaths = 'https://cdn.jsdelivr.net/npm/onnxruntime-web@1.19.2/dist/';

var ENGINE_NAME = /*__ENGINE_NAME__*/ "engine";
var ENGINE_AUTHOR = /*__ENGINE_AUTHOR__*/ "unknown";
var DEFAULT_MAX_DEPTH = /*__DEFAULT_DEPTH__*/ 1;
var DEFAULT_MOVETIME_MS = 8000;
var HARD_SAFETY_MS = 25000;
var MATE_SCORE = 100000;

var PLANES = ['P', 'N', 'B', 'R', 'Q', 'K', 'p', 'n', 'b', 'r', 'q', 'k'];

function encodePosition(c) {
  var data = new Float32Array(768);
  var board = c.board();
  for (var r = 0; r < 8; r++) {
    for (var f = 0; f < 8; f++) {
      var piece = board[r][f];
      if (!piece) continue;
      var symbol = piece.color === 'w' ? piece.type.toUpperCase() : piece.type;
      var planeIdx = PLANES.indexOf(symbol);
      var squareIdx = r * 8 + f;
      data[planeIdx * 64 + squareIdx] = 1.0;
    }
  }
  return data;
}

var session = null;
var modelError = null;
var modelReady = (async function initModel() {
  try {
    session = await ort.InferenceSession.create(ASSET_URLS['model.onnx']);
  } catch (e) {
    modelError = String(e && e.message ? e.message : e);
  }
})();

async function evaluateAsync(c) {
  if (c.in_checkmate()) return -MATE_SCORE;
  if (c.in_draw() || c.in_stalemate() || c.in_threefold_repetition()) return 0;
  if (!session) return 0; // model failed to load; caller already reported the error
  var input = new ort.Tensor('float32', encodePosition(c), [1, 768]);
  var results = await session.run({ input: input });
  var value = results.output.data[0];
  return value * 100; // pawn units -> centipawns
}

var chess = new Chess();
var searchState = { stop: false };

function send(line) {
  postMessage(line);
}

function toUciMove(move) {
  return move.from + move.to + (move.promotion || '');
}

function orderedMoves(c) {
  var moves = c.moves({ verbose: true });
  moves.sort(function (a, b) {
    var av = a.flags.indexOf('c') !== -1 ? 1 : 0;
    var bv = b.flags.indexOf('c') !== -1 ? 1 : 0;
    return bv - av;
  });
  return moves;
}

async function negamaxAsync(c, depth, alpha, beta, deadline, nodeCounter) {
  nodeCounter.count++;
  if (depth === 0 || c.game_over()) {
    return await evaluateAsync(c);
  }
  if (Date.now() > deadline) {
    searchState.stop = true;
    return await evaluateAsync(c);
  }
  var moves = orderedMoves(c);
  var best = -Infinity;
  for (var i = 0; i < moves.length; i++) {
    if (searchState.stop) break;
    c.move(moves[i]);
    var score = -(await negamaxAsync(c, depth - 1, -beta, -alpha, deadline, nodeCounter));
    c.undo();
    if (score > best) best = score;
    if (best > alpha) alpha = best;
    if (alpha >= beta) break;
  }
  return best;
}

async function searchBestMove(maxDepth, deadline, startTime, nodeCounter) {
  var best = null;
  var bestScore = 0;
  var rootMoves = orderedMoves(chess);
  if (rootMoves.length === 0) return { move: null, score: 0 };

  for (var d = 1; d <= maxDepth; d++) {
    var iterBest = null;
    var iterBestScore = -Infinity;
    var alpha = -Infinity;
    var beta = Infinity;
    for (var i = 0; i < rootMoves.length; i++) {
      if (Date.now() > deadline || searchState.stop) break;
      chess.move(rootMoves[i]);
      var score = -(await negamaxAsync(chess, d - 1, -beta, -alpha, deadline, nodeCounter));
      chess.undo();
      if (score > iterBestScore) {
        iterBestScore = score;
        iterBest = rootMoves[i];
      }
      if (score > alpha) alpha = score;
    }
    if (iterBest) {
      best = iterBest;
      bestScore = iterBestScore;
      var elapsed = Math.max(1, Date.now() - startTime);
      send(
        'info depth ' + d +
        ' score cp ' + Math.round(bestScore) +
        ' nodes ' + nodeCounter.count +
        ' nps ' + Math.round(nodeCounter.count / (elapsed / 1000)) +
        ' time ' + elapsed +
        ' pv ' + toUciMove(best)
      );
    }
    if (Date.now() > deadline || searchState.stop) break;
  }
  return { move: best, score: bestScore };
}

function handlePosition(parts) {
  var idx = 1;
  if (parts[idx] === 'startpos') {
    chess = new Chess();
    idx++;
  } else if (parts[idx] === 'fen') {
    var fenParts = parts.slice(idx + 1, idx + 7);
    chess = new Chess(fenParts.join(' '));
    idx += 7;
  }
  if (parts[idx] === 'moves') {
    idx++;
    for (; idx < parts.length; idx++) {
      var m = parts[idx];
      chess.move({ from: m.slice(0, 2), to: m.slice(2, 4), promotion: m.slice(4, 5) || undefined });
    }
  }
}

async function handleGo(parts) {
  searchState.stop = false;
  var depth = DEFAULT_MAX_DEPTH;
  var movetime = null;
  var infinite = false;
  for (var i = 1; i < parts.length; i++) {
    if (parts[i] === 'depth') depth = parseInt(parts[++i], 10);
    else if (parts[i] === 'movetime') movetime = parseInt(parts[++i], 10);
    else if (parts[i] === 'infinite') infinite = true;
  }
  await modelReady;
  if (modelError) {
    send('info string model load failed: ' + modelError);
    send('bestmove (none)');
    return;
  }
  var startTime = Date.now();
  var budget = movetime != null ? movetime : infinite ? HARD_SAFETY_MS : DEFAULT_MOVETIME_MS;
  var deadline = startTime + Math.min(budget, HARD_SAFETY_MS);
  var nodeCounter = { count: 0 };
  var result = await searchBestMove(depth, deadline, startTime, nodeCounter);
  send('bestmove ' + (result.move ? toUciMove(result.move) : '(none)'));
}

self.onmessage = function (ev) {
  var line = String(ev.data);
  var parts = line.split(/\\s+/).filter(Boolean);
  var cmd = parts[0];

  if (cmd === 'uci') {
    send('id name ' + ENGINE_NAME);
    send('id author ' + ENGINE_AUTHOR);
    send('uciok');
  } else if (cmd === 'isready') {
    modelReady.then(function () {
      send('readyok');
    });
  } else if (cmd === 'ucinewgame') {
    chess = new Chess();
  } else if (cmd === 'position') {
    handlePosition(parts);
  } else if (cmd === 'go') {
    handleGo(parts).catch(function (e) {
      send('info string search error: ' + (e && e.message ? e.message : e));
      send('bestmove (none)');
    });
  } else if (cmd === 'stop') {
    searchState.stop = true;
  }
};
`;

export function buildNnEntryJs({ name, author, defaultDepth = 1 }) {
  return TEMPLATE.replace('/*__ENGINE_NAME__*/ "engine"', JSON.stringify(name || "engine"))
    .replace('/*__ENGINE_AUTHOR__*/ "unknown"', JSON.stringify(author || "unknown"))
    .replace('/*__DEFAULT_DEPTH__*/ 1', String(defaultDepth));
}
